"""Added nickname to chat


Revision ID: 1a39a1ddc846
Revises: f688f8cc5c49
Create Date: 2025-05-14 16:39:51.915021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a39a1ddc846'
down_revision = 'f688f8cc5c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nick_name', sa.String(length=80), nullable=False))
        batch_op.drop_column('assignment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('nick_name')

    # ### end Alembic commands ###
