"""Rened station_log table to status_report

Revision ID: 4ed1c1e824ff
Revises: f53563a73224
Create Date: 2025-05-14 09:25:44.373110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed1c1e824ff'
down_revision = 'f53563a73224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=True),
    sa.Column('status_id', sa.String(length=36), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('delete_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['station_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('station_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_logs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('time', sa.DATETIME(), nullable=False),
    sa.Column('reporter_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('status_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('delete_flag', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['station_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('status_reports')
    # ### end Alembic commands ###
