"""Added more functionality to the chat

Revision ID: 5320d5ff929e
Revises: 1a39a1ddc846
Create Date: 2025-05-14 20:21:37.146881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5320d5ff929e'
down_revision = '1a39a1ddc846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('parent_message_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('message_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_rooms', ['room_id'], ['id'])
        batch_op.create_foreign_key(None, 'chat_messages', ['parent_message_id'], ['id'])
        batch_op.drop_column('uuid')

    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_activity', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('max_participants', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_private', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('moderators', sa.JSON(), nullable=True))
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=36), nullable=False))
        batch_op.drop_column('moderators')
        batch_op.drop_column('password')
        batch_op.drop_column('is_private')
        batch_op.drop_column('max_participants')
        batch_op.drop_column('last_activity')
        batch_op.drop_column('created_at')
        batch_op.drop_column('id')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_rooms', ['room_id'], ['uuid'])
        batch_op.drop_column('status')
        batch_op.drop_column('message_type')
        batch_op.drop_column('parent_message_id')
        batch_op.drop_column('edited_at')
        batch_op.drop_column('edited')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
