"""Added delete flag to observation_category table

Revision ID: aca2da0568fe
Revises: ee42b6f55280
Create Date: 2025-05-13 08:02:29.325141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca2da0568fe'
down_revision = 'ee42b6f55280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_flag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observations_categories', schema=None) as batch_op:
        batch_op.drop_column('delete_flag')

    # ### end Alembic commands ###
