"""Added delete flag to station status

Revision ID: ee42b6f55280
Revises: f9644fbaa214
Create Date: 2025-05-12 18:31:07.342490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee42b6f55280'
down_revision = 'f9644fbaa214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_flag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_statuses', schema=None) as batch_op:
        batch_op.drop_column('delete_flag')

    # ### end Alembic commands ###
