"""Updated form options tables to include sort order

Revision ID: f53563a73224
Revises: aca2da0568fe
Create Date: 2025-05-13 08:39:28.389109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53563a73224'
down_revision = 'aca2da0568fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.drop_column('display_name')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('observations_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.drop_column('delete_flag')

    with op.batch_alter_table('station_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.drop_column('delete_flag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_flag', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('observations_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_flag', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
