"""Updated Status Report Models

Revision ID: f9644fbaa214
Revises: f767aa8fbce2
Create Date: 2025-05-12 18:23:20.113696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9644fbaa214'
down_revision = 'f767aa8fbce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_statuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=True),
    sa.Column('status_id', sa.String(length=36), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('delete_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['station_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('station_logs')
    op.drop_table('station_statuses')
    # ### end Alembic commands ###
