"""Removed unique constraint on assignment_id to allow multiple volunteers per assignment

Revision ID: 2ac462b6e027
Revises: 4ef96ae76707
Create Date: 2025-10-13 17:48:53.149454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac462b6e027'
down_revision = '4ef96ae76707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffer_aro_volunteers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_staffer_aro_volunteers_assignment_id'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffer_aro_volunteers', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_staffer_aro_volunteers_assignment_id'), ['assignment_id'])

    # ### end Alembic commands ###
