"""Added staffer_aro_volunteers table for ARO volunteer mapping

Revision ID: 465f3f42a29f
Revises: 8b63db2a5beb
Create Date: 2025-10-12 15:34:21.007976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465f3f42a29f'
down_revision = '8b63db2a5beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffer_aro_volunteers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=True),
    sa.Column('callsign', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staffer_aro_volunteers')
    # ### end Alembic commands ###
