"""Added status and status_timestamp to staffer_aro_volunteers

Revision ID: 4ef96ae76707
Revises: 9048be8a274d
Create Date: 2025-10-13 16:56:38.174016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef96ae76707'
down_revision = '9048be8a274d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffer_aro_volunteers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffer_aro_volunteers', schema=None) as batch_op:
        batch_op.drop_column('status_timestamp')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
