"""Made assignment_id nullable and callsign unique in staffer_aro_volunteers

Revision ID: 51d212d45cbb
Revises: 465f3f42a29f
Create Date: 2025-10-12 16:09:56.816473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d212d45cbb'
down_revision = '465f3f42a29f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffer_aro_volunteers', schema=None) as batch_op:
        batch_op.alter_column('assignment_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('callsign',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_unique_constraint('uq_staffer_aro_volunteers_assignment_id', ['assignment_id'])
        batch_op.create_unique_constraint('uq_staffer_aro_volunteers_callsign', ['callsign'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffer_aro_volunteers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_staffer_aro_volunteers_callsign', type_='unique')
        batch_op.drop_constraint('uq_staffer_aro_volunteers_assignment_id', type_='unique')
        batch_op.alter_column('callsign',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('assignment_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###
