"""Added delete_flag to station_statuses

Revision ID: 6de5e732d4df
Revises: 2ac462b6e027
Create Date: 2025-10-13 17:58:52.058960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de5e732d4df'
down_revision = '2ac462b6e027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delete_flag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_statuses', schema=None) as batch_op:
        batch_op.drop_column('delete_flag')

    # ### end Alembic commands ###
