"""Added staffer_assignment_mappings table for manual mapping overrides

Revision ID: 79e224f07263
Revises: 51d212d45cbb
Create Date: 2025-10-12 17:07:14.146465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e224f07263'
down_revision = '51d212d45cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffer_assignment_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('imported_name', sa.String(length=200), nullable=True),
    sa.Column('imported_short_code', sa.String(length=50), nullable=True),
    sa.Column('assignment_id', sa.String(length=36), nullable=True),
    sa.Column('is_manual_override', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('imported_name IS NOT NULL OR imported_short_code IS NOT NULL', name='ck_staffer_assignment_mappings_has_identifier'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staffer_assignment_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staffer_assignment_mappings_imported_name'), ['imported_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_staffer_assignment_mappings_imported_short_code'), ['imported_short_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffer_assignment_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staffer_assignment_mappings_imported_short_code'))
        batch_op.drop_index(batch_op.f('ix_staffer_assignment_mappings_imported_name'))

    op.drop_table('staffer_assignment_mappings')
    # ### end Alembic commands ###
