"""Added color, icon, and description to station_statuses

Revision ID: 9048be8a274d
Revises: cc480f95c8df
Create Date: 2025-10-12 18:49:56.354855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9048be8a274d'
down_revision = 'cc480f95c8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_statuses', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('icon')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
