"""Added deleted flag to chat messages

Revision ID: bde3ef5838a3
Revises: b813a06ae119
Create Date: 2025-05-16 17:50:40.762970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde3ef5838a3'
down_revision = 'b813a06ae119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_flag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('deleted_flag')

    # ### end Alembic commands ###
