"""Added staffer_assignment field to staffer_aro_volunteers

Revision ID: cc480f95c8df
Revises: 79e224f07263
Create Date: 2025-10-12 18:30:57.820832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc480f95c8df'
down_revision = '79e224f07263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffer_aro_volunteers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staffer_assignment', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffer_aro_volunteers', schema=None) as batch_op:
        batch_op.drop_column('staffer_assignment')

    # ### end Alembic commands ###
