"""Initial migrations

Revision ID: f767aa8fbce2
Revises: 
Create Date: 2025-05-11 21:41:33.678294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f767aa8fbce2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('bib', sa.String(length=10), nullable=True),
    sa.Column('reporter_id', sa.String(length=36), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('agency_id', sa.String(length=36), nullable=True),
    sa.Column('agency_notified', sa.DateTime(), nullable=True),
    sa.Column('agency_arrival', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('delete_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('bib', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('reporter_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('delete_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['observations_categories.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observations')
    op.drop_table('events')
    op.drop_table('observations_categories')
    op.drop_table('assignments')
    op.drop_table('agencies')
    # ### end Alembic commands ###
